name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: matchai/waka-box
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 279142384e4034402d18ea6b994a6e46
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
